# Generated by Django 5.1.8 on 2025-05-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_created_at_post_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='taggroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
