# Generated by Django 5.1.11 on 2025-08-18 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_taggroup_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagGroupTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.tag')),
                ('tag_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.taggroup')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('tag_group', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='taggroup',
            name='tags_through',
            field=models.ManyToManyField(related_name='ordered_tag_groups', through='posts.TagGroupTag', to='posts.tag'),
        ),
    ]
