# Generated by Django 5.1.11 on 2025-08-19 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_populate_taggrouptag_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taggroup',
            name='tags',
        ),
    ]
