# Generated by Django 5.1.11 on 2025-08-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_remove_taggroup_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taggroup',
            name='tags_through',
        ),
        migrations.AddField(
            model_name='taggroup',
            name='tags',
            field=models.ManyToManyField(related_name='tag_groups', through='posts.TagGroupTag', to='posts.tag'),
        ),
    ]
