# Generated by Django 5.1.11 on 2025-08-21 10:17

import posts.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_remove_taggroup_tags_through_taggroup_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggroup',
            name='name',
            field=posts.fields.StrippedCharField(max_length=64),
        ),
    ]
