# Generated by Django 5.1.11 on 2025-08-21 10:34

from django.db import migrations


def strip_existing_names(apps, schema_editor):
    TagGroup = apps.get_model("posts", "TagGroup")
    for obj in TagGroup.objects.all():
        if obj.name and obj.name != obj.name.strip():
            TagGroup.objects.filter(pk=obj.pk).update(name=obj.name.strip())


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_alter_taggroup_name'),
    ]

    operations = [
        migrations.RunPython(strip_existing_names),
    ]
