# Generated by Django 5.1.11 on 2025-08-21 11:08

import posts.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_strip_taggroup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=posts.fields.StrippedCharField(max_length=100),
        ),
    ]
