# Generated by Django 5.1.11 on 2025-08-21 11:10

from django.db import migrations


def strip_existing_titles(apps, schema_editor):
    Post = apps.get_model("posts", "Post")
    for obj in Post.objects.all():
        if obj.title and obj.title != obj.title.strip():
            Post.objects.filter(pk=obj.pk).update(title=obj.title.strip())


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_alter_post_title'),
    ]

    operations = [
    ]
