# Generated by Django 5.2.6 on 2025-10-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_strip_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
