# Generated by Django 5.2.6 on 2025-10-01 13:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_alter_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(5000)]),
        ),
    ]
